# Categories & Filters Config

categories:
  - name: "Top Rated"
    filters:
      - name: "Rating > 8"
        type: "rating"
        value: 8.0

  - name: "By Genre"
    filters:
      - name: "Action"
        type: "genre"
        value: "Action"
      - name: "Drama"
        type: "genre"
        value: "Drama"
      - name: "Fantasy"
        type: "genre"
        value: "Fantasy"

  - name: "By Year"
    filters:
      - name: "2020s"
        type: "year"
        value: 2020
      - name: "2010s"
        type: "year"
        value: 2010
